# Generated by Django 6.0 on 2025-12-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-brands fa-python text-yellow-400', 'Python (Yellow)'), ('fa-brands fa-js text-yellow-300', 'JavaScript (Yellow)'), ('fa-brands fa-react text-blue-400', 'React (Blue)'), ('fa-solid fa-database text-indigo-400', 'Database/SQL (Indigo)'), ('fa-solid fa-server text-green-500', 'Django/Backend (Green)'), ('fa-solid fa-robot text-pink-500', 'AI/ML (Pink)'), ('fa-solid fa-cart-shopping text-orange-400', 'E-Commerce (Orange)'), ('fa-solid fa-layer-group text-purple-400', 'Full Stack (Purple)')], default='fa-solid fa-code', max_length=100)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
